from parser.models import SourceSpec


def build_sources() -> list[SourceSpec]:
    """Return curated source list and topic priorities for RAG dataset creation."""
    return [
        SourceSpec(
            category="basic_theory",
            subtopic="rag_foundations",
            url="https://arxiv.org/abs/2405.06211",
            source_type="arxiv",
            priority_topics=[
                "chunking strategies",
                "FAISS setup",
                "embeddings pipeline",
                "retrieval loop",
                "prompt design for RAG",
            ],
        ),
        SourceSpec(
            category="basic_theory",
            subtopic="rag_foundations",
            url="https://arxiv.org/abs/2409.14924",
            source_type="arxiv",
            priority_topics=[
                "chunking strategies",
                "FAISS setup",
                "embeddings pipeline",
                "retrieval loop",
                "prompt design for RAG",
            ],
        ),
        SourceSpec(
            category="basic_theory",
            subtopic="rag_foundations",
            url="https://arxiv.org/abs/2404.12457",
            source_type="arxiv",
            priority_topics=[
                "chunking strategies",
                "FAISS setup",
                "embeddings pipeline",
                "retrieval loop",
                "prompt design for RAG",
            ],
        ),
        SourceSpec(
            category="practical_tutorials",
            subtopic="huggingface_cookbook",
            url="https://huggingface.co/learn/cookbook/advanced_rag",
            source_type="docs",
            priority_topics=[
                "chunking strategies",
                "FAISS setup",
                "embeddings pipeline",
                "retrieval loop",
                "prompt design for RAG",
            ],
        ),
        SourceSpec(
            category="practical_tutorials",
            subtopic="huggingface_cookbook",
            url="https://huggingface.co/learn/cookbook/rag_zephyr_langchain",
            source_type="docs",
            priority_topics=[
                "chunking strategies",
                "FAISS setup",
                "embeddings pipeline",
                "retrieval loop",
                "prompt design for RAG",
            ],
        ),
        SourceSpec(
            category="embeddings_vector_db_core",
            subtopic="langchain_rag_tutorial",
            url="https://langchain-tutorials.github.io/langchain-rag-tutorial-2026/",
            source_type="docs",
            priority_topics=[
                "what embeddings are",
                "cosine similarity",
                "FAISS indexing",
                "similarity search process",
                "chunk storage design",
            ],
        ),
        SourceSpec(
            category="practical_repositories",
            subtopic="langchain_repo",
            url="https://github.com/langchain-ai/langchain",
            source_type="github",
            priority_topics=[
                "ingestion pipelines",
                "loaders",
                "retrieval chains",
                "multi-query RAG",
                "reranking pipelines",
            ],
        ),
        SourceSpec(
            category="practical_repositories",
            subtopic="llama_index_repo",
            url="https://github.com/run-llama/llama_index",
            source_type="github",
            priority_topics=[
                "ingestion pipelines",
                "loaders",
                "retrieval chains",
                "multi-query RAG",
                "reranking pipelines",
            ],
        ),
        SourceSpec(
            category="practical_repositories",
            subtopic="transformers_repo",
            url="https://github.com/huggingface/transformers",
            source_type="github",
            priority_topics=[
                "ingestion pipelines",
                "loaders",
                "retrieval chains",
                "multi-query RAG",
                "reranking pipelines",
            ],
        ),
        SourceSpec(
            category="embedding_theory",
            subtopic="sbert",
            url="https://www.sbert.net/",
            source_type="docs",
            priority_topics=[
                "how embeddings work",
                "semantic similarity",
                "difference between models",
                "normalization + cosine similarity",
            ],
        ),
        SourceSpec(
            category="embedding_theory",
            subtopic="mteb",
            url="https://huggingface.co/spaces/mteb/leaderboard",
            source_type="docs",
            priority_topics=[
                "how embeddings work",
                "semantic similarity",
                "difference between models",
                "normalization + cosine similarity",
            ],
        ),
        SourceSpec(
            category="advanced_rag_ideas",
            subtopic="langchain_blog_docs",
            url="https://python.langchain.com/docs/concepts/rag/",
            source_type="docs",
            priority_topics=[
                "multi-query retrieval",
                "reranking (cross-encoder)",
                "hybrid search (BM25 + vector search)",
                "self-RAG / agentic RAG",
            ],
        ),
        SourceSpec(
            category="advanced_rag_ideas",
            subtopic="llamaindex_blog",
            url="https://docs.llamaindex.ai/en/stable/optimizing/evaluation/evaluation/",
            source_type="docs",
            priority_topics=[
                "multi-query retrieval",
                "reranking (cross-encoder)",
                "hybrid search (BM25 + vector search)",
                "self-RAG / agentic RAG",
            ],
        ),
        SourceSpec(
            category="real_practical_reviews",
            subtopic="reddit_community",
            url="https://www.pinecone.io/learn/offline-evaluation/",
            source_type="docs",
            priority_topics=[
                "chunking problems",
                "embedding quality differences",
                "production RAG issues",
                "latency vs quality tradeoffs",
            ],
        ),
        SourceSpec(
            category="evaluation_metrics",
            subtopic="ragas_metrics",
            url="https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/",
            source_type="docs",
            priority_topics=[
                "recall@k",
                "precision@k",
                "faithfulness",
                "citation quality",
                "groundedness",
            ],
        ),
        SourceSpec(
            category="evaluation_metrics",
            subtopic="llamaindex_retrieval_eval",
            url="https://docs.llamaindex.ai/en/stable/examples/evaluation/retrieval/retriever_eval/",
            source_type="docs",
            priority_topics=[
                "retrieval evaluation",
                "mrr",
                "ndcg",
                "precision and recall",
                "top-k metrics",
            ],
        ),
        SourceSpec(
            category="evaluation_metrics",
            subtopic="deepset_haystack_rag_eval",
            url="https://haystack.deepset.ai/blog/rag-evaluation",
            source_type="blog",
            priority_topics=[
                "groundedness evaluation",
                "citation support",
                "end-to-end rag metrics",
                "hallucination prevention",
            ],
        ),
        SourceSpec(
            category="evaluation_robustness",
            subtopic="pinecone_rag",
            url="https://www.pinecone.io/learn/retrieval-augmented-generation/",
            source_type="docs",
            priority_topics=[
                "what is rag",
                "retriever and generator",
                "context window limits",
                "hallucination reduction",
            ],
        ),
        SourceSpec(
            category="evaluation_metrics",
            subtopic="pinecone_rag_evaluation",
            url="https://www.pinecone.io/learn/series/rag/rag-evaluation/",
            source_type="docs",
            priority_topics=[
                "recall@k",
                "precision@k",
                "mrr and ndcg",
                "groundedness and faithfulness",
                "citation support",
            ],
        ),
        SourceSpec(
            category="evaluation_robustness",
            subtopic="azure_rag_eval",
            url="https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/rag/rag-solution-design-and-evaluation-guide",
            source_type="docs",
            priority_topics=[
                "groundedness",
                "hallucination mitigation",
                "evaluation dimensions",
                "safety and refusal behavior",
            ],
        ),
        SourceSpec(
            category="evaluation_metrics",
            subtopic="ragas_faithfulness",
            url="https://docs.ragas.io/en/stable/concepts/metrics/faithfulness/",
            source_type="docs",
            priority_topics=[
                "faithfulness",
                "groundedness",
                "supported claims",
                "hallucination checks",
            ],
        ),
        SourceSpec(
            category="evaluation_metrics",
            subtopic="trulens_rag_triad",
            url="https://www.trulens.org/getting_started/core_concepts/rag_triad/",
            source_type="docs",
            priority_topics=[
                "context relevance",
                "groundedness",
                "answer relevance",
                "rag evaluation dimensions",
            ],
        ),
        SourceSpec(
            category="evaluation_robustness",
            subtopic="evidently_rag_eval",
            url="https://www.evidentlyai.com/llm-guide/rag-evaluation",
            source_type="docs",
            priority_topics=[
                "refusal behavior",
                "retrieval metrics",
                "groundedness",
                "evaluation under noise",
            ],
        ),
        SourceSpec(
            category="evaluation_robustness",
            subtopic="hf_rag_evaluation",
            url="https://huggingface.co/learn/cookbook/en/rag_evaluation",
            source_type="docs",
            priority_topics=[
                "duplicates and overlap",
                "groundedness",
                "retrieval evaluation",
                "dataset quality",
            ],
        ),
        SourceSpec(
            category="evaluation_robustness",
            subtopic="promptfoo_rag_eval",
            url="https://www.promptfoo.dev/docs/guides/evaluate-rag/",
            source_type="docs",
            priority_topics=[
                "citation support",
                "groundedness",
                "faithfulness checks",
                "retrieval evaluation",
            ],
        ),
        SourceSpec(
            category="evaluation_robustness",
            subtopic="confident_ai_rag_eval",
            url="https://www.confident-ai.com/blog/rag-evaluation-metrics-answer-relevancy-faithfulness-and-more",
            source_type="blog",
            priority_topics=[
                "faithfulness",
                "refusal behavior (i don't know)",
                "a/b evaluation",
                "rag quality metrics",
            ],
        ),
        SourceSpec(
            category="evaluation_robustness",
            subtopic="chroma_chunk_eval",
            url="https://research.trychroma.com/evaluating-chunking",
            source_type="docs",
            priority_topics=[
                "chunk overlap",
                "duplicate chunks",
                "retrieval/citation quality",
                "chunking evaluation",
            ],
        ),
        SourceSpec(
            category="data_indexing_ops",
            subtopic="langchain_indexing",
            url="https://python.langchain.com/docs/how_to/indexing/",
            source_type="docs",
            priority_topics=[
                "index freshness",
                "updating indexes",
                "incremental indexing",
                "stale data handling",
            ],
        ),
        SourceSpec(
            category="advanced_rag_ideas",
            subtopic="ibm_rag_overview",
            url="https://www.ibm.com/think/topics/retrieval-augmented-generation",
            source_type="docs",
            priority_topics=[
                "retrieval-augmented reasoning",
                "grounded generation",
                "citations and traceability",
                "rag architecture",
            ],
        ),
    ]

